name: kubernetes_deployment

description: execute an online endpoint for real time inference

inputs:
  flow_to_execute:
    description: "the flow to be registered and deployed"
    required: true
  DEPLOY_ENVIRONMENT:
    description: "env stage e.g. dev, test, prod"
    required: true
  CONNECTION_DETAILS:
    description: "PF connection details"
    required: false


runs:
  using: composite
  steps:
    - name: create local connections
      uses: ./.github/actions/execute_script
      with:
        step_name: "Create local PF connections"
        script_parameter: |
          python -m llmops.common.prompt_local_aoai_connection \
            --env_name ${{ inputs.DEPLOY_ENVIRONMENT }} \
            --flow_to_execute ${{ inputs.flow_to_execute }} \
            --connection_details '${{ inputs.CONNECTION_DETAILS }}'