trigger: none
pr:
  branches:
   include:
     - main
     - development
  paths:
    include:
      - .azure-pipelines/*
      - mlops/*
      - web_classification/*

pool:
  vmImage: ubuntu-latest

variables:
- group: mlops_platform_dev_vg

parameters:
 - name: env_name
   displayName: "Execution Environment"
   default: "pr"
 - name: model_type
   displayName: "model type"
   default: "web_classification"

stages:

  - template: ../../.azure-pipelines/platform_pr_dev_pipeline.yml
    parameters:
      exec_environment: ${{ parameters.env_name }}
      model_type: ${{ parameters.model_type }}