parameters:
- name: flow_to_execute
  type: string
- name: DEPLOY_ENVIRONMENT
  type: string
- name: CONNECTION_DETAILS
  type: string

steps:
- template: ./configure_azureml_agent.yml

- template: execute_python_code.yml
  parameters:
    step_name: "Create local Connection"
    script_parameter: |
      python -m llmops.common.prompt_local_aoai_connection \
        --env_name ${{ parameters.DEPLOY_ENVIRONMENT }} \
        --flow_to_execute ${{ parameters.flow_to_execute }} \
        --connection_details '${{ parameters.CONNECTION_DETAILS }}'

- task: AzureCLI@2
  displayName: "setup the build server"
  continueOnError: false
  inputs:
    azureSubscription: $(AZURE_RM_SVC_CONNECTION)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az extension add -n ml -y
      az upgrade --yes
      az config set extension.use_dynamic_install=yes_without_prompt

- task: AzureCLI@2
  displayName: Build Docker Image with flow artifacts
  continueOnError: false
  inputs: 
    azureSubscription: $(AZURE_RM_SVC_CONNECTION)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      