parameters:
- name: flow_to_execute
  type: string
- name: DEPLOY_ENVIRONMENT
  type: string
- name: CONNECTION_DETAILS
  type: string
- name: REGISTRY_DETAILS
  type: string
steps:
- template: configure_azureml_agent.yml
- template: execute_python_code.yml
  parameters:
    step_name: "Create local Connection"
    script_parameter: |
      python -m llmops.common.prompt_local_aoai_connection \
        --env_name ${{ parameters.DEPLOY_ENVIRONMENT }} \
        --flow_to_execute ${{ parameters.flow_to_execute }} \
        --connection_details '${{ parameters.CONNECTION_DETAILS }}'

- task: Bash@3
  displayName: Build Docker Image with flow artifacts
  continueOnError: false
  inputs: 
    targetType: filePath
    filePath: ./llmops/common/scripts/gen_docker_image.sh
  env:
    flow_to_execute: ${{ parameters.flow_to_execute }}
    deploy_environment: ${{ parameters.DEPLOY_ENVIRONMENT }}
    connection_details: ${{ parameters.CONNECTION_DETAILS }}
    registry_details: ${{ parameters.REGISTRY_DETAILS }}

