parameters:
- name: flow_to_execute
  type: string
- name: DEPLOY_ENVIRONMENT
  type: string

steps:
- template: templates/prepare_docker_image.yml
  parameters:
    flow_to_execute: ${{ parameters.flow_to_execute }}
    DEPLOY_ENVIRONMENT: ${{ parameters.DEPLOY_ENVIRONMENT }}


