pr: none
trigger:
  branches:
   include:
     - main
     - development
  paths:
    include:
      - .azure-pipelines/*
      - mlops/*
      - named_entity_recognition/*


pool:
  vmImage: ubuntu-latest

variables:
- group: mlops_platform_dev_vg

parameters:
 - name: env_name
   displayName: "Execution Environment"
   default: "dev"
 - name: model_type
   displayName: "model type"
   default: "named_entity_recognition"
 - name: IS_KUBERNETES_DEPLOYMENT
   displayName: "determine managed or kubernetes deployment"
   default: "False"

stages:

  - template: ../../.azure-pipelines/platform_ci_dev_pipeline.yml
    parameters:
      exec_environment: ${{ parameters.env_name }}
      model_type: ${{ parameters.model_type }}
      IS_KUBERNETES_DEPLOYMENT: ${{ parameters.IS_KUBERNETES_DEPLOYMENT }}