trigger: none
pr:
  branches:
   include:
     - main
     - development
  paths:
    include:
      - .azure-pipelines/*
      - llmops/*
      - named_entity_recognition/*

pool:
  vmImage: ubuntu-latest

variables:
- group: mlops_platform_dev_vg

parameters:
 - name: env_name
   displayName: "Execution Environment"
   default: "pr"
 - name: flow_to_execute
   displayName: "flow to execute"
   default: "named_entity_recognition"

stages:
  - template: ../../.azure-pipelines/platform_pr_dev_pipeline.yml
    parameters:
      exec_environment: ${{ parameters.env_name }}
      flow_to_execute: ${{ parameters.flow_to_execute }}