name: Prepare build environment

description: Prepares build environment for python and prompt flow related workflow execution.

inputs:
  versionSpec:
    description: "The Python version to use in the environment."
    default: "3.10"


runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.versionSpec }}

    - name: Load all prompt flow and related dependencies
      shell: bash
      run: |
        set -e # fail on error

        sudo apt-get remove azure-cli
        # curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

        sudo apt-get update
        sudo apt-get install ca-certificates curl apt-transport-https lsb-release gnupg

        sudo mkdir -p /etc/apt/keyrings
        curl -sLS https://packages.microsoft.com/keys/microsoft.asc |
        gpg --dearmor |
        sudo tee /etc/apt/keyrings/microsoft.gpg > /dev/null
        sudo chmod go+r /etc/apt/keyrings/microsoft.gpg

        AZ_DIST=$(lsb_release -cs)
        echo "deb [arch=`dpkg --print-architecture` signed-by=/etc/apt/keyrings/microsoft.gpg] https://packages.microsoft.com/repos/azure-cli/ $AZ_DIST main" |
        sudo tee /etc/apt/sources.list.d/azure-cli.list

        sudo apt-get update

        apt-cache policy azure-cli

        # Obtain the currently installed distribution
        AZ_DIST=$(lsb_release -cs)

        # Store an Azure CLI version of choice
        AZ_VER=2.52.0

        # Install a specific version
        sudo apt-get install azure-cli=$AZ_VER-1~$AZ_DIST

        python -m pip install --upgrade pip
        python -m pip install -r .github/requirements/execute_job_requirements.txt
        python -m pip install promptflow promptflow-tools promptflow-sdk jinja2 promptflow[azure] openai promptflow-sdk[builtins]

        az version