
parameters:
 - name: exec_environment
   displayName: "Execution Environment"
   default: "dev"
 - name: model_type
   displayName: "type of model to execute"

stages:
    - stage: build_validation
      displayName: build_validation
      jobs:
        - template: build_validation_pipeline.yml
          parameters:
            model_type: ${{ parameters.model_type }}

    - stage: execute_training_job
      displayName: execute_training_job
      dependsOn: 
      - build_validation
      jobs:
      - job: Execute_ml_Job_Pipeline
        steps:
        - template: templates/get_connection_details.yml

        - template: templates/configure_azureml_agent.yml
        
        - template: templates/register_data_asset.yml
          parameters:
            step_name: "register training data"
            script_parameter: |
              python -m mlops.common.register_data_asset \
                --subscription_id "$(SUBSCRIPTION_ID)" \
                --data_purpose "training_data" \
                --model_type ${{ parameters.model_type }} \
                --environment_name ${{ parameters.exec_environment }}

        - template: templates/execute_mlops_pipeline.yml
          parameters:
            script_parameter: |
              python -m mlops.common.prompt_pipeline \
                --subscription_id "$(SUBSCRIPTION_ID)" \
                --build_id $(BUILD.BUILDID) \
                --stage ${{parameters.exec_environment}} \
                --model_type ${{ parameters.model_type }} \
                --data_purpose "training_data" \
                --output_file run_id.txt
