
parameters:
 - name: exec_environment
   displayName: "Execution Environment"
   default: "dev"
 - name: flow_to_execute
   displayName: "type of model to execute"

stages:
    - stage: build_validation
      displayName: build_validation
      jobs:
        - template: build_validation_pipeline.yml
          parameters:
            flow_to_execute: ${{ parameters.flow_to_execute }}

    - stage: execute_training_job
      displayName: execute_training_job
      dependsOn: 
      - build_validation
      jobs:
      - job: Execute_ml_Job_Pipeline
        steps:
        - template: templates/get_connection_details.yml

        - template: templates/configure_azureml_agent.yml
        
        - template: templates/execute_python_code.yml
          parameters:
            step_name: "register training data"
            script_parameter: |
              python -m llmops.common.register_data_asset \
                --subscription_id "$(SUBSCRIPTION_ID)" \
                --data_purpose "training_data" \
                --flow_to_execute ${{ parameters.flow_to_execute }} \
                --env_name ${{ parameters.exec_environment }}

        - template: templates/execute_python_code.yml
          parameters:
            step_name: "Execute prompt job"
            script_parameter: |
              python -m llmops.common.prompt_pipeline \
                --subscription_id "$(SUBSCRIPTION_ID)" \
                --build_id $(BUILD.BUILDID) \
                --env_name ${{ parameters.exec_environment }} \
                --flow_to_execute ${{ parameters.flow_to_execute }} \
                --data_purpose "training_data" \
                --output_file run_id.txt
