pr: none
trigger:
  branches:
   include:
     - main
     - development
  paths:
    include:
      - .azure-pipelines/*
      - llmops/*
      - named_entity_recognition/*


pool:
  vmImage: ubuntu-latest

variables:
- group: llmops_platform_dev_vg

parameters:
 - name: exec_environment
   displayName: "Execution Environment"
   default: "dev"
 - name: flow_to_execute
   displayName: "type of model to execute"
 - name: deployment_type
   displayName: "determine type of deployment - aks, aml, webapp"

stages:
  - stage: deploy_prompts
    displayName: deploy_prompts
    jobs:
    - job: Execute_ml_Job_Pipeline
      steps:
      - ${{ if eq('webapp', lower(parameters.deployment_type)) }}:
        - template: templates/webapp_deployment.yml 
          parameters:
            flow_to_execute: ${{ parameters.flow_to_execute }}
            DEPLOY_ENVIRONMENT: ${{ parameters.exec_environment }}
            CONNECTION_DETAILS: '$(NAMED_ENTITY_RECOGNITION_AOAI_CONNECTIONS)'