name: test_workflow

on:
  workflow_call:
    inputs:
      env_name:
        type: string
        description: "Execution Environment"
        required: true
        default: "dev"
      flow_type:
        type: string
        description: "The flow use-case to execute"
        required: true
        default: "web_classification"
      deployment_type:
        type: string
        description:  "Determine type of deployment - aml, aks, webapp"
        required: true
    secrets:
      azure_credentials:
        description: "service principal authentication to Azure"
        required: true
      connection_details:
        description: "prompt flow connection details"
        required: false

jobs:
  deploy-flow:
    uses: ./.github/workflows/platform_cd_dev_workflow.yml
    with:
        env_name: ${{ inputs.env_name || 'dev'}}
        flow_type: ${{ inputs.flow_type || 'named_entity_recognition' }}
        deployment_type: ${{ inputs.deployment_type|| 'aml' }}
    secrets:
        azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
        connection_details: ${{ secrets.NAMED_ENTITY_RECOGNITION_AOAI_CONNECTIONS }}
